import type {
  BatterySalesShare,
  CustomerQuery,
  InventoryItem,
  KpiMetric,
  NotificationItem,
  Order,
  QueryStat,
  ReviewRequest,
  SalesPoint,
} from "@/types"

export const currentUser = {
  name: "Sarah Chen",
  email: "nina.v@example.com",
  role: "Operations Manager",
  initials: "SC",
}

export const kpiMetrics: KpiMetric[] = [
  {
    id: "queries",
    label: "Total Customer Queries",
    value: "1,284",
    change: "+12.4%",
    trend: "up",
    description: "vs last 7 days",
  },
  {
    id: "reviews",
    label: "Pending Human Reviews",
    value: "18",
    change: "-6.1%",
    trend: "down",
    description: "queue awaiting verification",
  },
  {
    id: "orders",
    label: "Orders Today",
    value: "47",
    change: "+8.0%",
    trend: "up",
    description: "confirmed across all branches",
  },
  {
    id: "stock",
    label: "Available Battery Stock",
    value: "3,612",
    change: "-2.3%",
    trend: "down",
    description: "units across warehouses",
  },
  {
    id: "revenue",
    label: "Revenue Generated",
    value: "$84,290",
    change: "+15.8%",
    trend: "up",
    description: "month to date",
  },
]

export const customerQueries: CustomerQuery[] = [
  {
    id: "Q-1048",
    customerName: "James Patel",
    email: "james.patel@example.com",
    message:
      "Need a replacement battery for my Dell XPS 15 7590. Original swollen after 3 years.",
    laptopModel: "Dell XPS 15 7590",
    batteryRequirement: "6-cell 97Wh Li-ion",
    confidence: 96,
    status: "Completed",
    date: "2026-08-18",
  },
  {
    id: "Q-1047",
    customerName: "Amelia Brooks",
    email: "amelia.brooks@example.com",
    message: "Does the HP Pavilion 15-cs3xxx take the TE03XL or TE04XL pack?",
    laptopModel: "HP Pavilion 15-cs3010",
    batteryRequirement: "TE03XL 41.7Wh",
    confidence: 71,
    status: "Human Review",
    date: "2026-08-18",
  },
  {
    id: "Q-1046",
    customerName: "Omar Haddad",
    email: "omar.haddad@example.com",
    message: "Looking for original Lenovo ThinkPad T480 battery, 3-cell preferred.",
    laptopModel: "Lenovo ThinkPad T480",
    batteryRequirement: "01AV423 24Wh 3-cell",
    confidence: 92,
    status: "Processing",
    date: "2026-08-18",
  },
  {
    id: "Q-1045",
    customerName: "Priya Raman",
    email: "priya.raman@example.com",
    message: "MacBook Pro 13 2017 battery replacement, need it by Friday.",
    laptopModel: "MacBook Pro 13 A1708",
    batteryRequirement: "A1713 54.5Wh",
    confidence: 98,
    status: "Completed",
    date: "2026-08-17",
  },
  {
    id: "Q-1044",
    customerName: "Liam O'Connor",
    email: "liam.oconnor@example.com",
    message: "ASUS ROG Strix G531 battery died. Can you ship to the airport branch?",
    laptopModel: "ASUS ROG Strix G531GT",
    batteryRequirement: "C41N1731 66Wh",
    confidence: 88,
    status: "Processing",
    date: "2026-08-17",
  },
  {
    id: "Q-1043",
    customerName: "Sofia Alvarez",
    email: "sofia.alvarez@example.com",
    message: "Need Acer Aspire 5 battery. Model sticker is faded, starts with AC14.",
    laptopModel: "Acer Aspire 5 A515",
    batteryRequirement: "AC14B8K 48Wh",
    confidence: 64,
    status: "Human Review",
    date: "2026-08-17",
  },
  {
    id: "Q-1042",
    customerName: "Noah Kim",
    email: "noah.kim@example.com",
    message: "Toshiba Satellite C55-C battery, original if possible.",
    laptopModel: "Toshiba Satellite C55-C",
    batteryRequirement: "PA5109U-1BRS 45Wh",
    confidence: 90,
    status: "Completed",
    date: "2026-08-16",
  },
  {
    id: "Q-1041",
    customerName: "Elena Rossi",
    email: "elena.rossi@example.com",
    message: "Surface Laptop 3 13.5 inch battery quote for 4 units.",
    laptopModel: "Microsoft Surface Laptop 3",
    batteryRequirement: "G3HTA040H 45.8Wh",
    confidence: 85,
    status: "Processing",
    date: "2026-08-16",
  },
]

export const recentQueries = customerQueries.slice(0, 5)

export const orders: Order[] = [
  {
    id: "ORD-8821",
    customerName: "James Patel",
    batteryModel: "C31N1815",
    quantity: 1,
    price: 129,
    branch: "Downtown Hub",
    status: "Delivered",
    date: "2026-08-18",
  },
  {
    id: "ORD-8820",
    customerName: "Priya Raman",
    batteryModel: "A1713",
    quantity: 1,
    price: 149,
    branch: "North Warehouse",
    status: "Processing",
    date: "2026-08-18",
  },
  {
    id: "ORD-8819",
    customerName: "Noah Kim",
    batteryModel: "PA5109U-1BRS",
    quantity: 2,
    price: 178,
    branch: "Airport Branch",
    status: "Confirmed",
    date: "2026-08-18",
  },
  {
    id: "ORD-8818",
    customerName: "Elena Rossi",
    batteryModel: "G3HTA040H",
    quantity: 4,
    price: 516,
    branch: "West Outlet",
    status: "Pending",
    date: "2026-08-17",
  },
  {
    id: "ORD-8817",
    customerName: "Liam O'Connor",
    batteryModel: "C41N1731",
    quantity: 1,
    price: 139,
    branch: "Airport Branch",
    status: "Confirmed",
    date: "2026-08-17",
  },
  {
    id: "ORD-8816",
    customerName: "Maya Singh",
    batteryModel: "01AV423",
    quantity: 3,
    price: 267,
    branch: "Downtown Hub",
    status: "Delivered",
    date: "2026-08-16",
  },
  {
    id: "ORD-8815",
    customerName: "Daniel Wright",
    batteryModel: "TE03XL",
    quantity: 1,
    price: 89,
    branch: "North Warehouse",
    status: "Processing",
    date: "2026-08-16",
  },
  {
    id: "ORD-8814",
    customerName: "Hana Suzuki",
    batteryModel: "L17C3PG1",
    quantity: 2,
    price: 198,
    branch: "West Outlet",
    status: "Pending",
    date: "2026-08-15",
  },
]

export const recentOrders = orders.slice(0, 5)

export const inventory: InventoryItem[] = [
  {
    id: "INV-01",
    batteryModel: "C31N1815",
    compatibleLaptop: "Dell XPS 15 7590",
    stockQuantity: 142,
    branch: "Downtown Hub",
    availability: "In Stock",
    unitPrice: 129,
  },
  {
    id: "INV-02",
    batteryModel: "A1713",
    compatibleLaptop: "MacBook Pro 13 A1708",
    stockQuantity: 38,
    branch: "North Warehouse",
    availability: "In Stock",
    unitPrice: 149,
  },
  {
    id: "INV-03",
    batteryModel: "TE03XL",
    compatibleLaptop: "HP Pavilion 15-cs3",
    stockQuantity: 12,
    branch: "West Outlet",
    availability: "Low Stock",
    unitPrice: 89,
  },
  {
    id: "INV-04",
    batteryModel: "01AV423",
    compatibleLaptop: "Lenovo ThinkPad T480",
    stockQuantity: 96,
    branch: "Downtown Hub",
    availability: "In Stock",
    unitPrice: 89,
  },
  {
    id: "INV-05",
    batteryModel: "C41N1731",
    compatibleLaptop: "ASUS ROG Strix G531",
    stockQuantity: 7,
    branch: "Airport Branch",
    availability: "Low Stock",
    unitPrice: 139,
  },
  {
    id: "INV-06",
    batteryModel: "AC14B8K",
    compatibleLaptop: "Acer Aspire 5 A515",
    stockQuantity: 0,
    branch: "North Warehouse",
    availability: "Out of Stock",
    unitPrice: 79,
  },
  {
    id: "INV-07",
    batteryModel: "PA5109U-1BRS",
    compatibleLaptop: "Toshiba Satellite C55",
    stockQuantity: 54,
    branch: "Airport Branch",
    availability: "In Stock",
    unitPrice: 89,
  },
  {
    id: "INV-08",
    batteryModel: "G3HTA040H",
    compatibleLaptop: "Surface Laptop 3 13.5",
    stockQuantity: 21,
    branch: "West Outlet",
    availability: "In Stock",
    unitPrice: 129,
  },
  {
    id: "INV-09",
    batteryModel: "L17C3PG1",
    compatibleLaptop: "Lenovo IdeaPad 330",
    stockQuantity: 4,
    branch: "Downtown Hub",
    availability: "Low Stock",
    unitPrice: 99,
  },
  {
    id: "INV-10",
    batteryModel: "A1322",
    compatibleLaptop: "MacBook Pro 13 A1278",
    stockQuantity: 0,
    branch: "West Outlet",
    availability: "Out of Stock",
    unitPrice: 119,
  },
]

export const reviewQueue: ReviewRequest[] = [
  {
    id: "RV-220",
    customerName: "Amelia Brooks",
    email: "amelia.brooks@example.com",
    message: "Does the HP Pavilion 15-cs3xxx take the TE03XL or TE04XL pack?",
    extracted: {
      brand: "HP",
      laptopModel: "HP Pavilion 15-cs3010",
      batteryModel: "TE03XL",
      specification: "11.55V 41.7Wh 3-cell",
      quantity: 1,
    },
    confidence: 71,
    receivedAt: "2026-08-18 09:14",
  },
  {
    id: "RV-219",
    customerName: "Sofia Alvarez",
    email: "sofia.alvarez@example.com",
    message: "Need Acer Aspire 5 battery. Model sticker is faded, starts with AC14.",
    extracted: {
      brand: "Acer",
      laptopModel: "Acer Aspire 5 A515-54",
      batteryModel: "AC14B8K",
      specification: "15.2V 48Wh 4-cell",
      quantity: 1,
    },
    confidence: 64,
    receivedAt: "2026-08-17 16:42",
  },
  {
    id: "RV-218",
    customerName: "Marcus Lee",
    email: "marcus.lee@example.com",
    message: "Battery for a Dell Inspiron, I think 15 3000 series from 2019.",
    extracted: {
      brand: "Dell",
      laptopModel: "Dell Inspiron 15 3593",
      batteryModel: "WDX0R",
      specification: "11.4V 42Wh 3-cell",
      quantity: 1,
    },
    confidence: 58,
    receivedAt: "2026-08-17 11:05",
  },
]

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    title: "Human review required",
    description: "Query Q-1047 confidence dropped below 75%.",
    time: "8 min ago",
    unread: true,
  },
  {
    id: "n2",
    title: "Low stock alert",
    description: "C41N1731 is down to 7 units at Airport Branch.",
    time: "24 min ago",
    unread: true,
  },
  {
    id: "n3",
    title: "Order confirmed",
    description: "ORD-8819 is ready for picking.",
    time: "1 hr ago",
    unread: false,
  },
  {
    id: "n4",
    title: "Daily digest",
    description: "47 orders processed today across 4 branches.",
    time: "3 hr ago",
    unread: false,
  },
]

export const salesOverview: SalesPoint[] = [
  { month: "Mar", revenue: 48200, orders: 310 },
  { month: "Apr", revenue: 52140, orders: 342 },
  { month: "May", revenue: 49880, orders: 328 },
  { month: "Jun", revenue: 61210, orders: 401 },
  { month: "Jul", revenue: 74550, orders: 468 },
  { month: "Aug", revenue: 84290, orders: 512 },
]

export const topBatteryModels: BatterySalesShare[] = [
  { model: "C31N1815", units: 186 },
  { model: "A1713", units: 154 },
  { model: "01AV423", units: 132 },
  { model: "TE03XL", units: 97 },
  { model: "C41N1731", units: 81 },
]

export const queryStats: QueryStat[] = [
  { status: "Completed", count: 842, fill: "var(--chart-2)" },
  { status: "Processing", count: 424, fill: "var(--chart-1)" },
  { status: "Human Review", count: 18, fill: "var(--chart-4)" },
]

export const orderCompletion = {
  completed: 86,
  pending: 9,
  cancelled: 5,
}

export const searchSuggestions = [
  { label: "Query Q-1047 Amelia Brooks", href: "/queries" },
  { label: "Order ORD-8821", href: "/orders" },
  { label: "Battery C41N1731 stock", href: "/inventory" },
  { label: "Pending reviews", href: "/review" },
]
